spring:
  datasource1:
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://아이피:포트/DB명?useSSL=false
         username: 아이디
         password: 비밀번호
         initial-size: 20
         min-idle: 20
         max-idle: 20
         max-active: 20
         max-wait: 3000
         pool-prepared-statements: true
         default-auto-commit: false
         validation-query: SELECT 1
         test-on-borrow: false
         test-on-return: false
         test-while-idle: true
         time-between-eviction-runs-millis: 3600000
         jmx-enabled: false
  datasource2:
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://아이피:포트/DB명?useSSL=false
         username: 아이디
         password: 비밀번호
         initial-size: 20
         min-idle: 20
         max-idle: 20
         max-active: 20
         max-wait: 3000
         pool-prepared-statements: true
         default-auto-commit: false
         validation-query: SELECT 1
         test-on-borrow: false
         test-on-return: false
         test-while-idle: true
         time-between-eviction-runs-millis: 3600000
         jmx-enabled: false
   



 
  
  
  
